### ISSUE TITLE
Render PDF page by page 

### ISSUE THREAD

**Issue by TRomesh** [agentcooper/react-pdf-annotator#1]
Is there a way to render the PDF document page by page instead of rendering the whole PDF file as a scroll-able vertical view?

**Comment by agentcooper** [comment]
It is not possible currently. I reuse the [viewer plugin by PDF.js](https://mozilla.github.io/pdf.js/web/viewer.html).

**Comment by ayush1852017** [comment]
@agentcooper 
You can use this code on the toggle.
![Screenshot from 2023-06-22 16-54-02](https://github.com/agentcooper/react-pdf-highlighter/assets/46336517/715bc25b-2853-4cc9-acd4-21096d9ef49b)

I am using `PDFSinglePageViewer` method of PDFjs.
Working fine for me.
