### ISSUE TITLE
Getting data from web service. not working

### ISSUE THREAD

**Issue by jfernal** [agentcooper/react-pdf-annotator#6]
Hello, i have an error when i have to setState with data from webservice.

  componentDidMount() {
    window.addEventListener(
      "hashchange",
      this.scrollToHighlightFromHash,
      false
    );
  request('GET', url_ws).done((res) => {
		if(res.statusCode==200){
			parseString(res.getBody(),{explicitArray:false}, function (err, result) {
				console.log(result['root']['element']);//getting data from xml and parsing to json
			    this.setState({ highlights: testHighlights});**//ERROR: Cannot read property 'setState'**  
			});
		}else{
			console.log("asd")
		}
  });

**Comment by agentcooper** [comment]
Hello.

This error has nothing to do with the package.

By taking a quick look at your code it seems that the problem is with the `function (err, result) {`. Try changing that to arrow function: `(err, result) => {`. Arrow functions preserve the context.

**Comment by jfernal** [comment]
Thank you @agentcooper
