### ISSUE TITLE
how to use it?

### ISSUE THREAD

**Issue by AdrianLsk** [agentcooper/react-pdf-annotator#8]
Hi @agentcooper, I have a noob question.

Is it implemented in typescript language? I am a bit confused by **strong typing** in the code.
NB: I am a javascript beginner.

**Comment by agentcooper** [comment]
Hey, @AdrianLsk.

The types are coming from [Flow](https://flow.org/) - static type checker for JavaScript.

With TypeScript you need to compile the whole project with the TS compiler to get JavaScript. With Flow you use [Babel plugin](https://babeljs.io/docs/plugins/preset-flow/) to strip off types and continue _transpiling_ as usual.

As a user of `react-pdf-annotator` you can either just use JS without caring about Flow or add Flow to your project and get the benefits of static type checking.

**Comment by AdrianLsk** [comment]
I see, got it! Thanks @agentcooper !
