### ISSUE TITLE
Cannon open others pdf files

### ISSUE THREAD

**Issue by jfernal** [agentcooper/react-pdf-annotator#9]
Hello i can't use others pdf files, you can try changing 

`state = {
    highlights: testHighlights[url] ? [...testHighlights[url]] : []
  };`
with 
`state = {
    highlights: []
  };`  

AND 
`const DEFAULT_URL = "https://arxiv.org/pdf/1708.08021.pdf";`
with 
`const DEFAULT_URL = "https://www.antennahouse.com/XSLsample/pdf/sample-link_1.pdf"`

Others url are not working these include mine, Could you help me?
https://depts.washington.edu/owrc/Handouts/Hacker-Sample%20MLA%20Formatted%20Paper.pdf
http://www.pdf995.com/samples/pdf.pdf

**Comment by agentcooper** [comment]
Your links do not work because they do not support [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS). This means JavaScript can't fetch them. You need to either serve them locally, from your domain or host them somewhere else.
